name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update file
        run: |
          echo "Last update: $(date)" >> log.txt

      - name: Commit and push
        run: |
          git config --global user.name "sandeepbihari2005"
          git config --global user.email "sandeepbihari2005@gmail.com"
          git add .
          git commit -m "Daily auto commit"
          git push
